### ISSUE TITLE
Add `build` metadata to `manifest.yaml`

### ISSUE THREAD

**Issue by MarkAckert** [zowe/keyring-utilities#14]
It would be nice to have a block of metadata in the `manifest.yaml` which contains build-time information that's easy to include in the final PAX archive. For example, updating manifest.yaml to contain:

```yaml
build:
  branch: "master"
  number: "123"
  commitHash: "12345...."
  timestamp: 1746717018543
```
